crystalsite/crystal_project/blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name='blog-post-list'),
    path('<int:year>/<int:month>/<slug:slug>', views.post_detail, name='blog-post-detail'),
    path('create/', views.post_new, name='blog-post-create'),
    path('<int:year>/<int:month>/<slug:slug>/update', views.PostUpdate.as_view(), name='blog-post-update'),
    path('<int:year>/<int:month>/<slug:slug>/delete', views.PostDelete.as_view(), name='blog-post-delete'),
    path('<int:year>/', views.PostArchiveYear.as_view(), name='blog-post-archive-year'),
    path('<int:year>/<int:month>/', views.PostArchiveMonth.as_view(), name='blog-post-archive-month'),
]

crystalsite/crystal_project/compendium/urls.py
from django.urls import path, include
from . import views  

urlpatterns = [
    path('crystal/', views.CrystalList.as_view(), name='compendium-crystal-list'),
    path('crystal/create', views.CrystalCreate.as_view(), name='compendium-crystal-create'),
    path('crystal/<slug:slug>', views.crystal_detail, name='compendium-crystal-detail'),
    path('crystal/<slug:slug>/update/', views.CrystalUpdate.as_view(), name='compendium-crystal-update'),
    path('crystal/<slug:slug>/delete/', views.CrystalDelete.as_view(), name='compendium-crystal-delete'),
    path('tag/', views.TagList.as_view(), name='compendium-tag-list'),
    path('tag/create/', views.TagCreate.as_view(), name='compendium-tag-create'),
    path('tag/<slug:slug>', views.tag_detail, name='compendium-tag-detail'),
    path('tag/<slug:slug>/update', views.TagUpdate.as_view(), name='compendium-tag-update'),
    path('tag/<slug:slug>/delete', views.TagDelete.as_view(), name='compendium-tag-delete'),
    path('', include('django.contrib.flatpages.urls')),
]

crystalsite/crystal_project/crystal_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView, TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='blog-post-list'), name='root'),
    path('compendium/', include('compendium.urls')),
    path('blog/', include('blog.urls')),
    path('rockhound/', include('rockHound.urls')),
    path('rockshop/', include('shophound.urls')),
    path('about/', TemplateView.as_view(template_name='site/about.html'), name='about-site'),
    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Crystal Compendium Admin'
admin.site.site_title = 'Crystal Compendium Site Admin'

crystalsite/crystal_project/compendium/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse('compendium-tag-detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('compendium-tag-update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('compendium-tag-delete', kwargs={'slug': self.slug})

class Crystal(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config')
    description = models.TextField()
    image = models.ImageField(upload_to="galleries", blank=True)
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('compendium-crystal-detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('compendium-crystal-update', kwargs={'slug': self.slug})
    
    def get_delete_url(self):
        return reverse('compendium-crystal-delete', kwargs={'slug': self.slug})

crystalsite/crystal_project/compendium/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Crystal, Tag

class SlugCleanMixin:
     def clean_slug(self):
        new_slug = (self.cleaned_data['slug'].lower())
        if (new_slug == 'create'):
            raise ValidationError('Slug may not be "create".')
        return new_slug

class CrystalForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Crystal
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name']

class TagForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()

crystalsite/crystal_project/compendium/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http.response import HttpResponse
from django.views.generic import TemplateView, View
from django.urls import reverse, reverse_lazy
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView


from .models import Crystal, Tag
from .forms import CrystalForm, TagForm
from .utils import ObjectCreateMixin, ObjectDeleteMixin, ObjectUpdateMixin

class CrystalList(View):
    page_kwarg = 'page'
    paginate_by = 5
    template_name = 'compendium/crystal_list.html'

    def get(self, request):
        crystals = Crystal.objects.all()
        paginator = Paginator(crystals, self.paginate_by)
        page_number = request.GET.get(self.page_kwarg)
        try: 
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        if page.has_previous():
            prev_url = "?{pkw}={n}".format(pkw=self.page_kwarg, n=page.previous_page_number())
        else:
            prev_url = None
        if page.has_next():
            next_url = "?{pkw}={n}".format(pkw=self.page_kwarg, n=page.next_page_number())
        else:
            next_url = None
        context = {
            'is_paginated': page.has_other_pages(),
            'next_page_url': next_url,
            'paginator': paginator,
            'prvious_page_url': prev_url,
            'crystal_list': page
        }
        return render(request, self.template_name, context)

def crystal_detail(request, slug):
    crystal = get_object_or_404(
        Crystal, slug__iexact=slug
    )
    return render(
        request,
        'compendium/crystal_detail.html',
        {'crystal': crystal}
    )

class TagList(View):
    page_kwarg = 'page'
    paginate_by = 5
    template_name = 'compendium/tag_list.html'

    def get(self, request):
        tags = Tag.objects.all()
        paginator = Paginator(tags, self.paginate_by)
        page_number = request.GET.get(self.page_kwarg)
        try: 
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        if page.has_previous():
            prev_url = "?{pkw}={n}".format(pkw=self.page_kwarg, n=page.previous_page_number())
        else:
            prev_url = None
        if page.has_next():
            next_url = "?{pkw}={n}".format(pkw=self.page_kwarg, n=page.next_page_number())
        else:
            next_url = None
        context = {
            'is_paginated': page.has_other_pages(),
            'next_page_url': next_url,
            'paginator': paginator,
            'previous_page_url': prev_url,
            'tag_list': page
        }
        return render(request, self.template_name, context)

def tag_list(request):
    return render(
        request,
        'compendium/tag_list.html',
        {'tag_list': Tag.objects.all()}
    )

def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    context = {
        'tag': tag,
    }
    return render(request, 'compendium/tag_detail.html', context)

class TagCreate(LoginRequiredMixin, CreateView):
    login_url = '/user/login/'
    form_class = TagForm
    template_name = 'compendium/tag_form.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            new_tag = bound_form.save()
            return redirect(new_tag)
        else:
            return render(request, self.template_name, {'form': bound_form})

class TagUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/user/login/'
    form_class = TagForm
    model = Tag
    template_name = ('compendium/tag_form_update.html')

class TagDelete(LoginRequiredMixin, DeleteView):
    login_url = '/user/login/'
    model = Tag
    success_url = reverse_lazy('compendium-tag-list')
    template_name = ('compendium/tag_confirm_delete.html')

class CrystalCreate(LoginRequiredMixin, TemplateView):
    login_url = '/user/login/'
    form_class = CrystalForm
    template_name = 'compendium/crystal_form.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request):
        bound_form = self.form_class(request.POST, request.FILES)
        if bound_form.is_valid():
            new_crystal = bound_form.save()
            return redirect(new_crystal)
        else:
            return render(request, self.template_name, {'form': bound_form})

class CrystalUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/user/login/'
    form_class = CrystalForm
    model = Crystal
    template_name = ('compendium/crystal_form_update.html')

class CrystalDelete(LoginRequiredMixin, DeleteView):
    login_url = '/user/login/'
    model = Crystal
    success_url = reverse_lazy('compendium-crystal-list')
    template_name = ('compendium/crystal_confirm_delete.html')        

crystalsite/crystal_project/compendium/templates/compendium/base_organizer.html
{% extends parent_template|default:'base.html' %}

crystalsite/crystal_project/compendium/templates/compendium/crystal_confirm_delete.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Delete Crystal
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary">
        <form action="{{ crystal.get_delete_url }}" method="POST">
            {% csrf_token %}
            <p>
                Are you sure you want to delete crystal {{ crystal.name }}?
            </p>
            <a class="button is-large is-fullwidth is-primary is-inverted" href="{{ crystal.get_absolute_url }}">Cancel</a>
            <br />
            <button class="button is-large is-fullwidth is-danger is-inverted" type="submit">Delete Crystal</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/crystal_detail.html
{% extends parent_template|default:'compendium/base_organizer.html' %}
{% load thumbnail %}
{% block title %}
{{ block.super }} - {{ crystal.name }}
{% endblock %}

{% block content %}


<div class="container" style="margin-bottom: 1.5rem;">
    <div class="container left">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a class="has-text-grey-light" href="{% url 'blog-post-list' %}">Home</a></li>
                <li><a class="has-text-grey-light" href="{% url 'compendium-crystal-list' %}">Crystals</a></li>
                <li class="has-text-grey-light is-active"><a href="#" aria-current="page">{{ crystal.name }}</a></li>
            </ul>
        </nav>
    </div>
</div>

<article class="content">
    <div class="columns notification is-primary">
        
        <div class="column is-four-fifths center">
            <h2 class="title is-2" style="font-family: Lobster">{{ crystal.name }}</h2>
        </div>
        <div class="column right">
            {% if perms.compendium.add_crystal %}
            <span><a href="{{ crystal.get_update_url }}">
                <span class="icon">
                    <i class="fas fa-pen-nib"></i>
                </span></a>
            <span><a href="{{ crystal.get_delete_url }}">
                <span class="icon">
                    <i class="fas fa-trash-alt"></i>
                </span></a>
            </span>
            {% endif %}
        </div>        
    </div>
</article>

<article>
    <div class="content columns">
        <div class="column is-half">
            <p>
                placeholder text
                {{ crystal.description|linebreaks }}
            </p>
        </div>

        <div class="media column">
            <figure class="media-right">
                <figure class="image">
                    {% if crystal.image %}
                        {% thumbnail crystal.image "480x480" as im %}
                            <img class="desktop" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"  alt="..."> 
                        {% endthumbnail %}
                    {% endif %}
                </figure>
            </figure>
        </div>

    </div>
</article>
<footer class="content">
    <div class="notification is-primary is-light">
        {% if crystal.blog_posts.all %}
            <section>
                <h3 class="title">Blog Post{{ crystal.blog_posts.all|pluralize }}</h3>
                <ul>
                    {% for post in crystal.blog_posts.all %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.title|title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
    </div>

</footer>


{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/crystal_form.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Create Crystal
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-large is-fullwidth is-primary is-inverted" type="submit">Create Crystal</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/crystal_form_update.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Update Crystal
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary">
        <form action="{{ crystal.get_update_url }}" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-large is-fullwidth is-primary is-inverted" type="submit">Update Crystal</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/crystal_list.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Crystals
{% endblock %}

{% block content %}

<div class="">
        <div class="container left">
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a class="has-text-grey-light" href="{% url 'blog-post-list' %}">Home</a></li>
                    <li class="has-text-grey-light is-active"><a href="#" aria-current="page">Crystals</a></li>
                </ul>
            </nav>
        </div>
</div>

<div class="context" >
    <div class="notification is-dark" style="padding-top: 1rem;">
        <div class="columns">
            <div class="column left" style="padding-bottom: 0.3rem;">
                <h2 class="title is-2 has-text-grey-light" style="font-family: Lobster">Crystal List</h2>
            </div>
            <div class="column">
                {% if perms.compendium.add_crystal %}
                <span class="right"><a href="{% url 'compendium-crystal-create' %}">
                    <span class="icon">
                        <i class="fas fa-pen-fancy" style="font-size: 30px"></i>
                    </span></a>
                </span>
                {% endif %}
            </div>
        </div>
        
        
        <div class="notification is-primary is-light">
            <div>
                {% for crystal in crystal_list %}
                <section class="section is-paddingless-horizontal" style="padding-top: 0; padding-bottom: 1rem;">
                    <div class="containter grid notification is-primary">
                        <article class="media center">
                            
                                <figure class="media-left">
                                    <figure class="center image is-128x128">
                                        {% if crystal.image %}
                                        <img class="is-rounded" src="{{ crystal.image.url }}" alt="{{ crystal.name }}">
                                        {% endif %}
                                    </figure>
                                </figure>
                            
                            <div class="media-content">
                                <div class="content columns">
                                    <div class="column left">
                                        <a class="title" style="font-family: Lobster" href="{{ crystal.get_absolute_url }}">
                                        {{ crystal.name }}</a>
                                    </div>
                                    <div class="column right">
                                        {% if perms.compendium.add_crystal %}
                                        <span><a href="{{ crystal.get_update_url }}">
                                        <span class="icon">
                                            <i class="fas fa-pen-nib"></i>
                                        </span></a>
                                        <span><a href="{{ crystal.get_delete_url }}">
                                            <span class="icon">
                                                <i class="fas fa-trash-alt"></i>
                                            </span></a>
                                        </span>
                                        {% endif %}

                                        
                                        
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                </section>

                {% empty %}
                    <em>No Crystals Available.</em>
                {% endfor %}
                {% if is_paginated %}
                <div class="content columns">
                    <div class="column left">
                        {% if crystal_list.has_previous %}
                        <span class="icon">
                            <a href="?page={{ crystal_list.previous_page_number }}">
                                <i class="fas fa-2x fa-angle-left"></i>
                            </a>
                        </span>  
                        {% endif %}
                    </div>
                    <div class="column center">
                        <p>
                            Page {{ crystal_list.number }}
                        of {{ paginator.num_pages }}
                        </p>
                    </div>
                    <div class="column right">
                        {% if crystal_list.has_next %}
                        <span class="icon">
                            <a href="{{ next_page_url }}">
                                <i class="fas fa-2x fa-angle-right"></i>
                            </a>
                        </span>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    
</div>

    

    
            

    





{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/tag_confirm_delete.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary">
        <form action="{{ tag.get_delete_url }}" method="POST">
            {% csrf_token %}
            <p>
                Are you sure you want to delete tag {{ tag.name }}?
            </p>
            <a class="button is-large is-fullwidth is-primary is-inverted" href="{{ tag.get_absolute_url }}">Cancel</a>
            <br />
            <button class="button is-large is-fullwidth is-danger is-inverted" type="submit">Delete Tag</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/tag_detail.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}

<div class="">
    <div class="container left">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a class="has-text-grey-light" href="{% url 'blog-post-list' %}" text-decoration="none;">Home</a></li>
                <li><a class="has-text-grey-light" href="{% url 'compendium-tag-list' %}" text-decoration="none;">Tags</a></li>
                <li class="has-text-grey-light is-active"><a href="#" aria-current="page">{{ tag.name|title }}</a></li>
            </ul>
        </nav>
    </div>
</div>

<div class="columns">
    <div class="column left" style="padding-bottom: 0.3rem;">
        <h2 class="title is-2 has-text-grey-light" style="font-family: Lobster">{{ tag.name|title }}</h2>
    </div>
    <div class="column">
        {% if perms.blog.add_tag %}
        <span class="right"><a href="{% url 'compendium-tag-create' %}">
            <span class="icon">
                <i class="fas fa-pen-fancy" style="font-size: 30px"></i>
            </span></a>
        </span>
        {% endif %}
    </div>
</div>


<article class="content">
    <div class="columns notification is-primary">
        <div class="column left">
            <h2 class="title">{{ tag.name|title }}</h2>
        </div>
        <div class="column right">
            {% if perms.compendium.add_tag %}
            <span><a href="{{ tag.get_update_url }}">
                <span class="icon">
                    <i class="fas fa-pen-nib"></i>
                </span></a>
            <span><a href="{{ tag.get_delete_url }}">
                <span class="icon">
                    <i class="fas fa-trash-alt"></i>
                </span></a>
            </span>
            {% endif %}
        </div>
        
    </div>
</article>


<footer class="content">
    <div class="notification is-primary is-light">
        {% if tag.crystal_set.all %}
        <p>
            {{ tag.name|title }} tag is associated with
            {{ tag.crystal_set.count }}
            crystal{{ tag.crystal_set.count|pluralize }}.
        </p>
        <ul>
            {% for crystal in tag.crystal_set.all %}
            <li><a href="{{ crystal.get_absolute_url }}">
                {{ crystal.name }}
            </a></li>
            {% endfor %}
        </ul>
        {% endif %}
        {% if tag.blog_posts.all %}
        <h3 class="title">Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
            <ul>
                {% for post in tag.blog_posts.all %}
                    <li><a href="{{ post.get_absolute.url }}">
                        {{ post.title|title }}
                    </a></li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if not tag.crystal_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
        {% endif %}
    </div>
</footer>


{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/tag_form.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
<div class="content">
    <div>
        <form class="box notification is-primary" action="{% url 'compendium-tag-create' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-large is-fullwidth is-primary is-inverted" type="submit">Create Tag</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/tag_form_update.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Update Tag
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary">
        <form action="{{ tag.get_update_url }}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-large is-fullwidth is-primary is-inverted" type="submit">Update Tag</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/compendium/templates/compendium/tag_list.html
{% extends parent_template|default:'compendium/base_organizer.html' %}

{% block title %}
{{ block.super }} - Tags
{% endblock %}

{% block content %}

<div class="">
    <div class="container left">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a class="has-text-grey-light" href="{% url 'blog-post-list' %}" text-decoration="none;">Home</a></li>
                <li class="has-text-grey-light is-active"><a href="#" aria-current="page">Tags</a></li>
            </ul>
        </nav>
    </div>
</div>

<div class="columns">
    <div class="column left" style="padding-bottom: 0.3rem;">
        <h2 class="title is-2 has-text-grey-light" style="font-family: Lobster">All Tags</h2>
    </div>
    <div class="column">
        {% if perms.blog.add_tag %}
        <span class="right"><a href="{% url 'compendium-tag-create' %}">
            <span class="icon">
                <i class="fas fa-pen-fancy" style="font-size: 30px"></i>
            </span></a>
        </span>
        {% endif %}
    </div>
</div>

<div class="content">
    <div class="notification is-dark">
    
        <div class="notification is-primary is-light">
            <div>
                {% for tag in tag_list %}
                <div class="columns notification is-primary">
                    <div class="column is-four-fifths center">
                        <a class="title" href="{{ tag.get_absolute_url }} ">
                            {{ tag.name|title}}
                        </a>
                    </div>
                    <div class="column right">
                        {% if perms.compendium.add_tag %}
                        <span><a href="{{ tag.get_update_url }}">
                            <span class="icon">
                                <i class="fas fa-pen-nib"></i>
                            </span></a>
                        <span><a href="{{ tag.get_delete_url }}">
                            <span class="icon">
                                <i class="fas fa-trash-alt"></i>
                            </span></a>
                        </span>
                        {% endif %}
                    </div>
                </div>
                <br />
                {% empty %}
                    <li><em>There are currently no Tags available.</em></li>
                {% endfor %}

                {% if is_paginated %}
                <div class="content columns">
                    <div class="column left">
                        {% if previous_page_url %}
                            <span class="icon">
                                <a href="?page={{ tag_list.previous_page_number }}">
                                    <i class="fas fa-2x fa-angle-left"></i>
                                </a>
                            </span>   
                        {% endif %}
                    </div>
                    <div class="column center">
                        <p>
                            Page {{ tag_list.number }}
                            of {{ paginator.num_pages }}
                        </p>  
                    </div>
                    <div class="column right">
                        {% if tag_list.has_next %}
                            <span class="icon">
                                <a href="{{ next_page_url }}">
                                    <i class="fas fa-2x fa-angle-right"></i>
                                </a>
                            </span>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}