crystalsite/crystal_project/blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name='blog-post-list'),
    path('<int:year>/<int:month>/<slug:slug>', views.post_detail, name='blog-post-detail'),
    path('create/', views.post_new, name='blog-post-create'),
    path('<int:year>/<int:month>/<slug:slug>/update', views.PostUpdate.as_view(), name='blog-post-update'),
    path('<int:year>/<int:month>/<slug:slug>/delete', views.PostDelete.as_view(), name='blog-post-delete'),
    path('<int:year>/', views.PostArchiveYear.as_view(), name='blog-post-archive-year'),
    path('<int:year>/<int:month>/', views.PostArchiveMonth.as_view(), name='blog-post-archive-month'),
]

crystalsite/crystal_project/crystal_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView, TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='blog-post-list'), name='root'),
    path('compendium/', include('compendium.urls')),
    path('blog/', include('blog.urls')),
    path('rockhound/', include('rockHound.urls')),
    path('rockshop/', include('shophound.urls')),
    path('about/', TemplateView.as_view(template_name='site/about.html'), name='about-site'),
    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Crystal Compendium Admin'
admin.site.site_title = 'Crystal Compendium Site Admin'

crystalsite/crystal_project/blog/models.py
from django.db import models
from django.urls import reverse
from compendium.models import Crystal, Tag
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(
        max_length=63,
        help_text='use lowercase, alpha-numeric characters and replace all spaces with underscores',
        unique_for_month='pub_date'
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField()
    pub_date = models.DateField(
        'date published',
        auto_now_add=True
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        help_text='hold CTRL to select more than 1 tag',
        related_name='blog_posts'
        )
    crystals = models.ManyToManyField(
        Crystal,
        blank=True,
        help_text='hold CTRL to select more than 1 crystal',
        related_name='blog_posts'
        )

    class Meta:
        verbose_name = 'blog post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'

    def __str__(self):
        return "{} on {}".format(
            self.title, 
            self.pub_date.strftime('%Y-%m-%d')
        )
    
    def get_absolute_url(self):
        return reverse('blog-post-detail', kwargs={'year': self.pub_date.year, 'month': self.pub_date.month, 'slug': self.slug})

    def get_update_url(self):
        return reverse('blog-post-update', kwargs={'year': self.pub_date.year, 'month': self.pub_date.month, 'slug': self.slug})
    
    def get_delete_url(self):
        return reverse('blog-post-delete', kwargs={'year': self.pub_date.year, 'month': self.pub_date.month, 'slug': self.slug})

    def get_archive_year_url(self):
        return reverse('blog-post-archive-year', kwargs={'year': self.pub_date.year})

    def get_archive_month_url(self):
        return reverse('blog-post-archive-month', kwargs={'year': self.pub_date.year, 'month': self.pub_date.month})

crystalsite/crystal_project/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

crystalsite/crystal_project/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import CreateView, ListView, View
from django.views.generic.dates import ArchiveIndexView, MonthArchiveView, YearArchiveView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post
from .forms import PostForm

@login_required(login_url='/user/login/')
@permission_required('blog.add_post')
def post_new(request):
    if request.method=="POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('blog-post-list')
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form})
        

def post_edit(request, year, month, slug):
    pass    

class PostCreate(CreateView):
    form_class = PostForm
    model = Post

class PostList(ArchiveIndexView):
    allow_empty = True
    allow_future = True
    context_object_name = 'post_list'
    date_field = 'pub_date'
    make_object_list = True
    model = Post
    paginate_by = 10
    template_name = 'blog/post_list.html'

class OldPostList(View):

    def get(self, request):
        return render(
        request,
        'blog/post_list.html',
        {'post_list': Post.objects.all()}
    )

def post_list(request):
    return render(
        request,
        'blog/post_list.html',
        {'post_list': Post.objects.all()}
    )

def post_detail(request, year, month, slug):
    post = get_object_or_404(
        Post,
        pub_date__year=year,
        pub_date__month=month,
        slug=slug
        )
    return render(request, 'blog/post_detail.html', {'post': post})

class OldPostCreate(View):
    form_class = PostForm
    template_name = 'blog/post_form.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            new_post = bound_form.save()
            return redirect(new_post)
        else:
            return render(request, self.template_name, {'form': bound_form})


class PostUpdate(LoginRequiredMixin, View):
    login_url = '/user/login/'
    form_class = PostForm      
    model = Post      
    template_name = 'blog/post_form_update.html'

    def get_object(self, year, month, slug):
        return get_object_or_404(
            self.model,
            pub_date__year=year,
            pub_date__month=month,
            slug=slug)

    def get(self, request, year, month, slug):
        post = self.get_object(year, month, slug)
        context = {
            'form': self.form_class(instance=post), 
            'post': post, 
            }
        return render(request, self.template_name, context)

    def post(self, request, year, month, slug):
        post = self.get_object(year, month, slug)
        bound_form = self.form_class(request.POST, instance=post)
        if bound_form.is_valid():
            new_post = bound_form.save()
            return redirect(new_post)
        else:
            context = {
                'form': bound_form,
                'post': post,
            }
            return render(request, self.template_name, context)

class PostDelete(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request, year, month, slug):
        post = get_object_or_404(
            Post,
            pub_date__year=year,
            pub_date__month=month,
            slug=slug
            )
        return render(request, 'blog/post_confirm_delete.html', {'post': post})

    def post(self, request, year, month, slug):
        post = get_object_or_404(
            Post,
            pub_date__year=year,
            pub_date__month=month,
            slug=slug
            )
        post.delete()
        return redirect('blog_post_list')

class PostArchiveYear(YearArchiveView):
    model = Post
    date_field = 'pub_date'
    make_object_list = True

class PostArchiveMonth(MonthArchiveView):
    model = Post
    date_field = 'pub_date'
    month_format = '%m'

crystalsite/crystal_project/blog/templates/blog/base_blog.html
{% extends parent_template|default:'base.html' %}

crystalsite/crystal_project/blog/templates/blog/post_archive_month.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - {{ month|date:"F Y" }} Posts
{% endblock %}

{% block content %}

<div class="">
    <div class="container left">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a class="has-text-grey-light" href="{% url 'blog-post-list' %}" text-decoration="none;">Home</a></li>
                <li class="has-text-grey-light"><a href="{% url 'blog-post-archive-year' month|date:'Y' %}">{{ month|date:"Y" }} Posts</a></li>
                <li class="has-text-grey-light is-active"><a href="#" aria-current="page">{{ month|date:"F Y" }} Posts</a></li>
            </ul>
        </nav>
    </div>
</div>

<div class="columns">
    <div class="column left" style="padding-bottom: 0.3rem;">
        <h2 class="title is-2 has-text-grey-light" style="font-family: Lobster">All Posts for {{month|date:'F Y'}}</h2>
    </div>
    <div class="column">
        {% if perms.blog.add_post %}
        <span class="right"><a href="{% url 'blog-post-create' %}">
            <span class="icon">
                <i class="fas fa-pen-fancy" style="font-size: 30px"></i>
            </span></a>
        </span>
        {% endif %}
    </div>
</div>

<div class="content"></div>
    <div class="notification is-dark">

        {% for post in post_list %}
            <article>
                <header>
                    <div class="columns notification is-primary">
                        <div class="column left">
                            <h2 class="title"><a href="{{ post.get_absolute_url }}">
                                {{ post.title|title}}
                            </a></h2>
                            
                        </div>
                        <div class="column center">
                            <p class="subtitle is-6">
                                Written on
                                <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                                    {{ post.pub_date|date:"l, F j, Y" }}
                                </time>
                            </p>
                
                        </div>
                        <div class="column">
                            {% if perms.blog.add_post %}
                            <span class="right"><a href="{{ post.get_update_url }}">
                                <span class="icon">
                                    <i class="fas fa-pen-nib"></i>
                                </span></a>
                            <span class="right"><a href="{{ post.get_delete_url }}">
                                <span class="icon">
                                    <i class="fas fa-trash-alt"></i>
                                </span></a>
                            </span>
                            {% endif %}
                        </div>
                    </div>
                </header>
                <article class="media notification is-primary is-light">
                    <p>{{ post.text|truncatewords:20 }}</p>
                    <p>
                        <a href="{{ post.get_absolute_url }}">
                            Read more&hellip;
                        </a>
                    </p>
                </article>
            </article>
            <br/>
        {% endfor %}
        <footer>
            <div class="notification is-primary is-light">
                <p><a href="{%url 'blog-post-archive-year' month|date:'Y' %}">
                    All Posts from {{ month|date:'Y' }}
                </a></p>
                <p><a href="{% url 'blog-post-list' %}">
                    Latest Posts
                </a></p>
            {% if previous_month %}
                <ul>
            
                    <li>
                        <a href="{% url 'blog-post-archive-month' previous_month|date:'Y' previous_month|date:'m' %}">
                            Post from {{ previous_month|date:'F Y' }}
                        </a>
                    </li>
            {% endif %}
            {% if next_month %}
                <li>
                    <a href="{% url 'blog-post-archive-month' next_month|date:'Y' next_month|date:'m' %}">
                        Post from {{ next_month|date:'F Y' }}
                    </a>
                </li>
            </ul>
            {% endif %}
            </div>
        </footer>

{% endblock %}

crystalsite/crystal_project/blog/templates/blog/post_archive_year.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - {{ year|date:"Y" }} Posts
{% endblock %}

{% block content %}

<div class="">
    <div class="container left">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a class="has-text-grey-light" href="{% url 'blog-post-list' %}" text-decoration="none;">Home</a></li>
                <li class="has-text-grey-light is-active"><a href="#" aria-current="page">{{ year|date:"Y" }} Posts</a></li>
            </ul>
        </nav>
    </div>
</div>

<div class="columns">
    <div class="column left" style="padding-bottom: 0.3rem;">
        <h2 class="title is-2 has-text-grey-light" style="font-family: Lobster">All Posts for {{ year|date:"Y" }}</h2>
    </div>
    <div class="column">
        {% if perms.blog.add_post %}
        <span class="right"><a href="{% url 'blog-post-create' %}">
            <span class="icon">
                <i class="fas fa-pen-fancy" style="font-size: 30px"></i>
            </span></a>
        </span>
        {% endif %}
    </div>
</div>


<div class="content">
    <div class="notification is-dark">
        
        {% for post in post_list %}
            <article>
                <header>
                    <div class="columns notification is-primary is-paddingless">
                        <div class="column left">
                            <h2 class="title"><a href="{{ post.get_absolute_url }}">
                                {{ post.title|title}}
                            </a></h2>
                            
                        </div>
                        <div class="column center">
                            <p class="subtitle is-6">
                                Written on
                                <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                                    {{ post.pub_date|date:"l, F j, Y" }}
                                </time>
                            </p>
                
                        </div>
                        <div class="column">
                            {% if perms.blog.add_post %}
                            <span class="right"><a href="{{ post.get_update_url }}">
                                <span class="icon">
                                    <i class="fas fa-pen-nib"></i>
                                </span></a>
                            <span class="right"><a href="{{ post.get_delete_url }}">
                                <span class="icon">
                                    <i class="fas fa-trash-alt"></i>
                                </span></a>
                            </span>
                            {% endif %}
                        </div>
                    </div>
                </header>
                <article class="media notification is-primary is-light">
                    <p>{{ post.text|truncatewords:20 }}</p>
                    <p>
                        <a href="{{ post.get_absolute_url }}">
                            Read more&hellip;
                        </a>
                    </p>
                </article>
            </article>
            <br/>
        {% endfor %}

        <footer>
            <div class="notification is-primary is-light">
                <h3 class="title">Archives by Month</h3>
                <ul>
                    {% for m in date_list %}
                        <li>
                            <a href="{% url 'blog-post-archive-month' m|date:'Y' m|date:'m' %}">
                                {{ m|date:"F Y" }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            
            {% if previous_year %}
                <ul>
            
                    <li>
                        <a href="{% url 'blog-post-archive-year' previous_year|date:'Y' %}">
                            Post from {{ previous_year|date:"Y"}}
                        </a>
                    </li>
            {% endif %}
            {% if next_year %}
                <li>
                    <a href="{% url 'blog-post-archive-year' next_year|date:'Y' %}">
                        Post from {{ next_year|date:"Y"}}
                    </a>
                </li>
            </ul>
            {% endif %}
            </div>
        </footer>
{% endblock %}

crystalsite/crystal_project/blog/templates/blog/post_confirm_delete.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - Delete Post
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary center">
        <form action="{{ post.get_delete_url }}" method="POST">
            {% csrf_token %}
            <p class="lobster is-size-3"><em>
                Are you sure you want to delete post {{ post.name }}?</em>
            </p>
            <a class="button is-large is-fullwidth is-primary is-inverted" href="{{ post.get_absolute_url }}">Cancel</a>
            <br />
            <button class="button is-large is-fullwidth is-danger is-inverted" type="submit">Delete Post</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/blog/templates/blog/post_detail.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - {{ post.title|title }}
{% endblock %} 

{% block content %}

<div class="container" style="padding: 1rem;">
    <div class="container left">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a class="has-text-grey-light" href="{% url 'blog-post-list' %}">Home</a></li>
                <li class="has-text-grey-light is-active"><a href="#" aria-current="page">{{ post.title}}</a></li>
            </ul>
        </nav>
    </div>
</div>

<div class="left" style="padding-bottom: 1rem;">
    <h2 class="title is-2 has-text-grey-light" style="font-family: Lobster">{{ post.author }}</h2>
</div>



<article class="content is-medium">
    <header>
        <div class="columns notification is-primary">
            <div class="column left">
                <h2 class="title">{{ post.title|title }}</h2>
            
            </div>
            <div class="column center">
                
    
            </div>
            
            <div class="column">
                {% if perms.blog.add_post %}
                <span class="right"><a href="{{ post.get_update_url }}">
                    <span class="icon">
                        <i class="fas fa-pen-nib"></i>
                    </span></a>
                <span class="right"><a href="{{ post.get_delete_url }}">
                    <span class="icon">
                        <i class="fas fa-trash-alt"></i>
                    </span></a>
                </span>
                {% endif %}
            </div>
        </div>
    </header>
    <main>
        <div class="notification is-light">
            <p class="content is-small right">
                <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                   {{ post.pub_date|date:"l, F j, Y" }}
               </time>
           </p><hr>
           <p class="content">
                {{ post.text|linebreaks }}
            </p>
        </div>

    </main>
        

{% if post.crystals.all or post.tags.all %}
    <footer>
        <div class="notification is-primary is-light">
        {% if post.crystals.all %}
            <section>
                <h5>Crystal{{post.crystals.count|pluralize }}</h3>
                <ul>
                    {% for crystal in post.crystals.all %}
                        <li><a href="{{ crystal.get_absolute_url }}">
                            {{ crystal.name }}
                        </a></li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

        {% if post.tags.all %}
            <section>
                <h5>Tag{{ post.tags.count|pluralize }}</h3>
                <ul>
                    {% for tag in post.tags.all %}
                        <li><a href="{{ tag.get_absolute_url }}">
                            {{ tag.name|title }}
                        </a></li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
        </div>
    </footer>

{% endif %}
</article>
{% endblock %}

crystalsite/crystal_project/blog/templates/blog/post_form.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - Create Blog Post
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary">
        <form action="{% url 'blog-post-create' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-large is-fullwidth is-primary is-inverted" type="submit">Create Post</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/blog/templates/blog/post_form_update.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - Update Post
{% endblock %}

{% block content %}
<div class="content">
    <div class="notification is-primary">
        <form action="{{ post.get_update_url }}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-large is-fullwidth is-primary is-inverted" type="submit">Update Post</button>
        </form>
    </div>
</div>
{% endblock %}

crystalsite/crystal_project/blog/templates/blog/post_list.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - Posts
{% endblock %}

{% block content %}

<div class="">
    <div class="container left">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li class="has-text-grey is-active"><a href="#" aria-current="page">Home</a></li>
            </ul>
        </nav>
    </div>
</div>

<div class="columns">
    <div class="column left" style="padding-bottom: 0.3rem;">
        <h2 class="title is-2 has-text-grey-light" style="font-family: Lobster">Blog List</h2>
    </div>
    <div class="column">
        {% if perms.blog.add_post %}
        <span class="right"><a href="{% url 'blog-post-create' %}">
            <span class="icon">
                <i class="fas fa-pen-fancy" style="font-size: 30px"></i>
            </span></a>
        </span>
        {% endif %}
    </div>
</div>

{% for post in post_list %}
    <article class="content">
        <header>
            <div class="columns notification is-primary">
                <div class="column left">
                    <h2 class="title "><a href="{{ post.get_absolute_url }}">
                        {{ post.title|title}}
                    </a></h2>
                    <div class="columns is-mobile">
                        
                    </div>
                </div>
                
                
                <div class="column">
                    {% if perms.blog.change_post %}
                    <span class="right"><a href="{{ post.get_update_url }}">
                        <span class="icon">
                            <i class="fas fa-pen-nib"></i>
                        </span></a>
                    </span>
                    <span class="right"><a href="{{ post.get_delete_url }}">
                        <span class="icon">
                            <i class="fas fa-trash-alt"></i>
                        </span></a>
                    </span>
                    {% endif %}
                    <div class="columns">
                        <div class="column">
                            <p class="content title is-4">
                                <strong>by </strong>{{ post.author }}
                            </p>
                        </div>
                        <div class="column right">
                            <p class="content">
                                 <strong> on </strong><time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                                    {{ post.pub_date|date:"l, F j, Y" }}
                                </time>
                            </p>
                        </div>
                    </div>
                </div>
                
            </div>
                
        </header>

        <article class="media notification is-light">
            <br /><br />
            <p>{{ post.text|truncatewords:20 }}</p>
            <p>
                <a href="{{ post.get_absolute_url }}">
                    Read more&hellip;
                </a>
            </p>
        </article>
    </article>
    {% empty %}
        <p><em>No blog posts available.</em></p>
{% endfor %}

<footer>
    <div class="notification is-primary is-light">
        <div>
            <h3 class="title">Post Archives</h3>
            <ul>
                {% for y in date_list %}
                    <li>
                        <a href="{% url 'blog-post-archive-year' y|date:'Y' %}">
                            {{ y|date:'Y' }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        
{% endblock %}